[project]
name = "cloud-dtc-docker"
version = "0.1.0"
description = "Pipeline to run cloud-dtc tools"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pytest"]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = ["."]